@baseUrl = http://localhost:5177
@username = asd
@password = asd

### create user
POST {{baseUrl}}/api/User
Content-Type: application/json

{
    "UserLoginName": "{{username}}",
    "UserPassword": "{{password}}"
}

### login

# @name login
POST {{baseUrl}}/api/Token
Content-Type: application/json

{
    "UserLoginName": "{{username}}",
    "UserPassword": "{{password}}"
}

### refresh

# @name refresh
POST {{baseUrl}}/api/Token/refresh
Content-Type: application/json

{
    "refreshToken": "{{login.response.body.refreshToken}}"
}

### create group

POST {{baseUrl}}/api/Groups
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "GroupDisplayName": "myGroup",
    "GroupPassword": "hehehehaw"
}


### join group

POST {{baseUrl}}/api/Groups/join
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "GroupId": "f0e1fa8f-0e85-4b75-a554-c235a04f5a92",
    "GroupPassword": "hehehehaw"
}

### get group

GET {{baseUrl}}/api/group/48e75e47-ca84-4751-8f77-e79126d36d57
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json


### get groups

GET {{baseUrl}}/api/group
Authorization: Bearer {{login.response.body.token}}

### get wishlits

GET {{baseUrl}}/api/group/ff0f5751-e1e0-4c5f-82ec-4f6db6863740/wishlist
Authorization: Bearer {{login.response.body.token}}

### get cards

GET {{baseUrl}}/api/group/ff0f5751-e1e0-4c5f-82ec-4f6db6863740/wishlist/4dd94a31-a357-4a15-81c1-875873f67387/card
Authorization: Bearer {{login.response.body.token}}

### batch group
GET {{baseUrl}}/api/batch/group/ff0f5751-e1e0-4c5f-82ec-4f6db6863740
Authorization: Bearer {{login.response.body.token}}
