@baseUrl = http://localhost:5177
@username = teamy

### create user
POST {{baseUrl}}/api/User
Content-Type: application/json

{
    "UserLoginName": "{{username}}",
    "UserPassword": "beans"
}

### login

# @name login
POST {{baseUrl}}/api/Token
Content-Type: application/json

{
    "UserLoginName": "{{username}}",
    "UserPassword": "beans"
}

### create group

POST {{baseUrl}}/api/Groups
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "GroupDisplayName": "myGroup",
    "GroupPassword": "hehehehaw"
}


### join group

POST {{baseUrl}}/api/Groups/join
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "GroupId": "f0e1fa8f-0e85-4b75-a554-c235a04f5a92",
    "GroupPassword": "hehehehaw"
}

### get groups

GET {{baseUrl}}/api/Groups
Authorization: Bearer {{login.response.body.token}}
